=== bart-group/BART/tests/CLETUSTests/edlValidation_rules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="edlRules">
        <xs:annotation> 
            <xs:documentation xml:lang="en">
                Be careful: parameter ids must be unique to be evaluated in literals! 
				
				Rules Syntax
			    ------------
				Allowed arithmetic operators are: +,-,/,*                                                        
         		EXAMPLE: ((rxp0*rxp1 + rxp2) == (rxp1))
				
				
				Allowed relational operators are: ==                                                          
                For others use available comparison functions instead (edlValidation_biggerThan, edlValidation_lowerThan, ...)  
				EXAMPLE: (rxp0 == rxp1)
				
				Allowed functions are:                                                                            
                                                                                                          
				edlValidation_exists(arg)                                                                      
				edlValidation_strIsEqual(arg1,arg2)
				
				edlValidation_lowerThan(arg1,arg2)                                                               
				EXAMPLE: (edlValidation_lowerThan(rxp3,rxp4))                                 
				 
				edlValidation_equalOrLowerThan(arg1,arg2 )
				EXAMPLE: (edlValidation_equalOrLowerThan(rxp3,rxp4))

				edlValidation_biggerThan(arg1,arg2)                                                              
				EXAMPLE: (edlValidation_biggerThan(rxp3,rxp4))

				edlValidation_equalOrBiggerThan(arg1,arg2 )
				EXAMPLE: (edlValidation_equalOrBiggerThan(rxp3,rxp4))

				Don't use multiple comparisons in literals:                                                      
				NEVER DO: (rxp1 == rxp2 == rxp1)
				
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="rule"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

	<xs:element name="rule">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="param"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="premise"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="conclusion"/>
				<xs:element minOccurs="1" maxOccurs="1" ref="message"/>
			</xs:sequence>
			<xs:attribute name="ruleID" use="required" type="xs:ID"/>
		</xs:complexType>
	</xs:element>

    <xs:element name="param">
        <xs:complexType>
            <xs:sequence>
                 <xs:element minOccurs="1" maxOccurs="1" name="paramRef"  type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="pID" use="required" type="xs:ID"/>
            <xs:attribute name="pName" use="optional"  type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="premise">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded"  ref="literal"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="conclusion">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="1" ref="literal"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="literal"  type="xs:string">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Literals are the base units of premises and conclusions. Every Literal must be solvable to TRUE or FALSE.
            </xs:documentation>
       </xs:annotation>
    </xs:element>

    <xs:element name="message"  type="xs:string"/>
  
</xs:schema>

=== bart-group/BART/tests/CLETUSTests/edlValidation_rules.xml
<?xml version="1.0"  encoding="UTF-8"?>

<edlRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="edlValidation_rules.xsd">

<!--  ENVIRONMENT INTERNAL -->
	<!-- If logging is activated a logfile has to be given. -->
	<rule ruleID="r1_1">
		<param pID="r1_1p1" pName="r1_1A">
			<paramRef>
				rtExperiment.environment{1}.logging{1}.ATTRIBUTE.doLogging
			</paramRef>
		</param>
		<param pID="r1_1p2" pName="r1_1B">
			<paramRef>
				rtExperiment.environment{1}.logging{1}.logFile{1}.CONTENT
			</paramRef>
		</param>
		<premise>
			<literal>edlValidation_strIsEqual(r1_1p1,'true')</literal>
		</premise>
		<conclusion>
			<literal>edlValidation_exists(r1_1p2)</literal>
		</conclusion>
		<message>
			Edl Error: doLogging = "true" but no logFile is given!
		</message>
	</rule>
	
    <!-- If Environment- output image modalities image type is set to "IMAGE"   file extension must be ".ima" -->
	<rule ruleID="r1_2">
		<param pID="r1_2p1" pName="">
			<paramRef>
				rtExperiment.environment{1}.resultImage{1}.imageModalities{1}.ATTRIBUTE.imgType
			</paramRef>
		</param>
		<param pID="r1_2p2" pName="">
			<paramRef>
				rtExperiment.environment{1}.resultImage{1}.imageModalities{1}.ATTRIBUTE.imgDataExtension
			</paramRef>
		</param>
		<premise>
			<literal>edlValidation_strIsEqual(r1_2p1,'IMAGE')</literal>
		</premise>
		<conclusion>
			<literal>edlValidation_strIsEqual(r1_2p2,'.ima')</literal>
		</conclusion>
		<message>
			Edl Error: Environment- output image data is defined as IMAGE, but file
			extension is not ".ima"!
		</message>
	</rule>

	<!-- If Environment- output image modalities image type is set to "DICOM"   file extension must be ".dcm" -->
	<rule ruleID="r1_3">
		<param pID="r1_3p1" pName="">
			<paramRef>
				rtExperiment.environment{1}.resultImage{1}.imageModalities{1}.ATTRIBUTE.imgType
			</paramRef>
		</param>
		<param pID="r1_3p2" pName="">
			<paramRef>
				rtExperiment.environment{1}.resultImage{1}.imageModalities{1}.ATTRIBUTE.imgDataExtension
			</paramRef>
		</param>

		<premise>
			<literal>edlValidation_strIsEqual(r1_3p1,'DICOM')</literal>
		</premise>

		<conclusion>
			<literal>edlValidation_strIsEqual(r1_3p2,'.dcm')</literal>
		</conclusion>

		<message>
			Edl Error: Environment- output image data is defined as DICOM, but file
			extension is not ".dcm"!
		</message>
	</rule>

	<!-- If Environment- output image modalities image type is set to "ANALYZE"   file extension must be ".hdr" -->
	<rule ruleID="r1_4">
		<param pID="r1_4p1" pName="">
			<paramRef>
				rtExperiment.environment{1}.resultImage{1}.imageModalities{1}.ATTRIBUTE.imgType
			</paramRef>
		</param>
		<param pID="r1_4p2" pName="">
			<paramRef>
				rtExperiment.environment{1}.resultImage{1}.imageModalities{1}.ATTRIBUTE.imgDataExtension
			</paramRef>
		</param>

		<premise>
			<literal>edlValidation_strIsEqual(r1_4p1,'ANALYZE')</literal>
		</premise>

		<conclusion>
			<literal>edlValidation_strIsEqual(r1_4p2,'.hdr')</literal>
		</conclusion>

		<message>
			Edl Error: Environment- output image data is defined as ANALYZE, but file
			extension is not ".img"!
		</message>
	</rule>
<!-- END  ENVIRONMENT INTERNAL -->



<!-- EXPERIMENT DATA -->

	<!-- The size of gw design + ignored scans at startup must be equal to MR param MR_TAG_MEASUREMENTS -->
	<rule ruleID="r2">
		<param pID="r2p1" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.gwDesignStruct
			</paramRef>
		</param>
		<param pID="r2p2" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.gwDesignStruct{1}.scanBasedRegressor
			</paramRef>
		</param>
		<param pID="r2p3" pName="">
			<paramRef>
				rtExperiment.mriParams{1}.MR_TAG_MEASUREMENTS{1}.CONTENT
			</paramRef>
		</param>

		<param pID="r2p4" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.gwDesignStruct{1}.scanBasedRegressor{1}.ATTRIBUTE.size
			</paramRef>
		</param>
		<param pID="r2p5" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.ATTRIBUTE.ignoreScansAtStart
			</paramRef>
		</param>

		<premise>
			<literal>edlValidation_exists(r2p1)</literal>
			<literal>edlValidation_exists(r2p2)</literal>
			<literal>edlValidation_exists(r2p3)</literal>
		</premise>

		<conclusion>
			<literal>(r2p4+r2p5) == (r2p3)</literal>
		</conclusion>

		<message>
			Edl Error: Number of measurments (MR_TAG_MEASUREMENTS) does
			not fit to number of scans in GW design! Missed ignored
			scans?
		</message>
	</rule>



	<!-- The size of a growing window scanbased regressor is exactly: sbrdesign size * repetitions + all random ignored images -->
	<rule ruleID="r2_1">
		<param pID="r2_1p1" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.gwDesignStruct
			</paramRef>
		</param>
		<param pID="r2_1p2" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.gwDesignStruct{1}.scanBasedRegressor
			</paramRef>
		</param>

		<param pID="r2_1p3" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.gwDesignStruct{1}.scanBasedRegressor{1}.sbrDesign{1}.ATTRIBUTE.size
			</paramRef>
		</param>
		<param pID="r2_1p4" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.gwDesignStruct{1}.scanBasedRegressor{1}.sbrDesign{1}.ATTRIBUTE.repetitions
			</paramRef>
		</param>
		<param pID="r2_1p5" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.gwDesignStruct{1}.scanBasedRegressor{1}.ATTRIBUTE.size
			</paramRef>
		</param>
		<param pID="r2_1p6" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.gwDesignStruct{1}.scanBasedRegressor{1}.sbrIgnoreStruct{1}.ATTRIBUTE.overallIgnores
			</paramRef>
		</param>

		<premise>
			<literal>edlValidation_exists(r2_1p1)</literal>
			<literal>edlValidation_exists(r2_1p2)</literal>
		</premise>

		<conclusion>
			<literal>(r2_1p3*r2_1p4+r2_1p6) == (r2_1p5)</literal>
		</conclusion>

		<message>
			Edl Error: Check size of scanBasedRegressor and size of
			sbrDesign in gwDesignStruct! Missed ignored scans?
		</message>
	</rule>


<!-- The length of a growing window time based regressor is exactly: tbrDesign length * repetitions  -->
	<rule ruleID="r2_2">
		<param pID="r2_2p1" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.gwDesignStruct
			</paramRef>
		</param>
		<param pID="r2_2p2" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.gwDesignStruct{1}.timeBasedRegressor
			</paramRef>
		</param>

		<param pID="r2_2p3" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.gwDesignStruct{1}.timeBasedRegressor{1}.tbrDesign{1}.ATTRIBUTE.length
			</paramRef>
		</param>
		<param pID="r2_2p4" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.gwDesignStruct{1}.timeBasedRegressor{1}.tbrDesign{1}.ATTRIBUTE.repetitions
			</paramRef>
		</param>
  	<param pID="r2_2p5" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.gwDesignStruct{1}.timeBasedRegressor{1}.ATTRIBUTE.length
			</paramRef>
		</param>  
		<premise>
			<literal>edlValidation_exists(r2_2p1)</literal>
			<literal>edlValidation_exists(r2_2p2)</literal>
		</premise>

		<conclusion>
			<literal>(r2_2p3*r2_2p4) == (r2_2p5)</literal>
		</conclusion>

		<message>
			Edl Error: Check size of timeBasedRegressor Nr.1 and size of
			tbrDesign in gwDesignStruct! Missed repetitions?
		</message>
	</rule>
  
  
  
  <!-- The length of a sliding window time based regressor is exactly: tbrDesign length * repetitions  -->
	<rule ruleID="r2_3">
		<param pID="r2_3p1" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.swDesignStruct
			</paramRef>
		</param>
		<param pID="r2_3p2" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.swDesignStruct{1}.timeBasedRegressor
			</paramRef>
		</param>

		<param pID="r2_3p3" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.swDesignStruct{1}.timeBasedRegressor{1}.tbrDesign{1}.ATTRIBUTE.length
			</paramRef>
		</param>
		<param pID="r2_3p4" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.swDesignStruct{1}.timeBasedRegressor{1}.tbrDesign{1}.ATTRIBUTE.repetitions
			</paramRef>
		</param>
  	<param pID="r2_3p5" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.swDesignStruct{1}.timeBasedRegressor{1}.ATTRIBUTE.length
			</paramRef>
		</param>  
		<premise>
			<literal>edlValidation_exists(r2_3p1)</literal>
			<literal>edlValidation_exists(r2_3p2)</literal>
		</premise>

		<conclusion>
			<literal>(r2_3p3*r2_3p4) == (r2_3p5)</literal>
		</conclusion>

		<message>
			Edl Error: Check size of timeBasedRegressor Nr.1 and size of
			tbrDesign in swDesignStruct! Missed repetitions?
		</message>
	</rule>
  
  <!-- The length of a growing window time based regressor{2} is exactly: tbrDesign length * repetitions  -->
	<rule ruleID="r2_4">
		<param pID="r2_4p1" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.gwDesignStruct
			</paramRef>
		</param>
		<param pID="r2_4p2" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.gwDesignStruct{1}.timeBasedRegressor{2}
			</paramRef>
		</param>

		<param pID="r2_4p3" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.gwDesignStruct{1}.timeBasedRegressor{2}.tbrDesign{1}.ATTRIBUTE.length
			</paramRef>
		</param>
		<param pID="r2_4p4" pName="">
			<paramRef>
				rtExperiment.experimentData{1}.paradigm{1}.gwDesignStruct{1}.timeBasedRegressor{2}.tbrDesign{1}.ATTRIBUTE.repetitions
			</paramRef>
		</param>
  	<param pID="r2_4p5" pName="">
			<paramRef>
